### ISSUE TITLE
Atualização do Mk Docks 

### ISSUE THREAD

**Issue by Ninja-Haiyai** [unb-mds/Gastos-DF-Squad12#42]
Adicionar a documentação do projeto para o MK Docs e adicionar seu link no readme para facilitar o acesso da documentação as pessoas interessadas no projeto

**Comment by Vini47** [comment]
vou aproveitar e refatorar o readme da main deixar ele mais enxuto e simples pois atualmente ele esta bagunçado e com informações desconexas. apenas deixando registrado aqui pois não acho que seja necessário uma isse so para isso.
