### ISSUE TITLE
refazer o front

### ISSUE THREAD

**Issue by Vini47** [unb-mds/Gastos-DF-Squad12#62]
refazer o front pois ele esta muito mal feito com imagens desconexas e fontes quase entrado uma na outra e uma complexidade de modelo sem necessidade e sem padrão de cores.

escolha fontes bonitas faça isso com cores bonitas e discretas. 

exemplo de fontes sem um bom entre linhas:
![image](https://github.com/user-attachments/assets/125482eb-a0d2-41e7-b807-60431c5befb8)

eu imagine um front mais simples e direto como o projeto se dispõe a ser, fiz esse modelo bem simples no daw.io so para imaginar e seguirem como modelo mas isso não é lei se tiverem ideias melhores e modificações podem fazer isso é so uma sugestão.

![image](https://github.com/user-attachments/assets/00179ba2-e8d6-4523-9d87-d6e410c37711)

a imagem é bem explicativa e posteriormente exibe os gráficos na tela neste modelo:

![image](https://github.com/user-attachments/assets/c2297905-34b1-44e1-b0e5-c8e4275f6b7b)

**Comment by Ninja-Haiyai** [comment]
Esse entre linhas aí é do próprio CSS utilizado, dá pra aumentar a distância entre as linhas no css, mas irei fazer a refatoração do front levando em consideração essas orientações
